version: "3"

services:
  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    ports:
      - 7000:7000
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/home/node
